//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsc2020Session1App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.DelegateFlights = new HashSet<DelegateFlight>();
            this.HelperFlights = new HashSet<HelperFlight>();
        }
    
        public int id { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Flight1 { get; set; }
        public System.DateTime Dep_Date { get; set; }
        public System.TimeSpan Dep_Time { get; set; }
        public System.TimeSpan Arr_Time { get; set; }
        public string Class { get; set; }
        public int Seats { get; set; }
        public decimal Price_SGD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelegateFlight> DelegateFlights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelperFlight> HelperFlights { get; set; }
    }
}
