//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsc2020Session1App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Helper()
        {
            this.HelperFlights = new HashSet<HelperFlight>();
        }
    
        public int Helper_ID { get; set; }
        public string Helper_Name { get; set; }
        public System.TimeSpan Available_From { get; set; }
        public System.TimeSpan Available_To { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelperFlight> HelperFlights { get; set; }
    }
}
