//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsc2020Session1App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wsc2020Session1DbContext : DbContext
    {
        public wsc2020Session1DbContext()
            : base("name=wsc2020Session1DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DelegateFlight> DelegateFlights { get; set; }
        public virtual DbSet<Delegate> Delegates { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<HelperFlight> HelperFlights { get; set; }
        public virtual DbSet<Helper> Helpers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
